"use client";

import { useEffect, useMemo, useState } from "react";
import { Plus } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input, Label, Select, Textarea } from "@/components/ui/input";
import { Callout } from "@/components/ui/callout";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";

interface Source { providerId: string; providerName: string; type: string; baseUrl: string; boundKeys: { id: string; name: string; keyPreview: string }[] }

export function ChannelCreateDialog({ siteId, onCreated }: { siteId: string; onCreated: () => void }) {
  const [open, setOpen] = useState(false), [sources, setSources] = useState<Source[]>([]), [providerId, setProviderId] = useState(""), [boundKeyId, setBoundKeyId] = useState(""), [name, setName] = useState(""), [baseUrl, setBaseUrl] = useState(""), [models, setModels] = useState(""), [group, setGroup] = useState("default"), [priority, setPriority] = useState("0"), [error, setError] = useState<string | null>(null), [saving, setSaving] = useState(false);
  const provider = sources.find((item) => item.providerId === providerId);
  const modelList = useMemo(() => models.split(/[\n,]+/).map((item) => item.trim()).filter(Boolean), [models]);
  useEffect(() => { if (!open) return; void fetch(`/api/channels/${encodeURIComponent(siteId)}/sources`, { cache: "no-store" }).then(async (r) => { const j = await r.json(); if (!r.ok) throw new Error(j.error || "读取上游来源失败"); setSources(j.data || []); }).catch((e) => setError(e instanceof Error ? e.message : "读取上游来源失败")); }, [open, siteId]);
  const chooseProvider = (id: string) => { setProviderId(id); const next = sources.find((item) => item.providerId === id); setBaseUrl(next?.baseUrl || ""); setBoundKeyId(next?.boundKeys[0]?.id || ""); };
  const submit = async () => { if (!providerId || !boundKeyId || !name.trim() || !baseUrl.trim() || !modelList.length) return setError("请填写来源、名称、Base URL 和至少一个模型"); if (!window.confirm(`确认在当前下游创建渠道“${name.trim()}”吗？`)) return; setSaving(true); setError(null); try { const r = await fetch(`/api/channels/${encodeURIComponent(siteId)}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ providerId, boundKeyId, name: name.trim(), type: 1, baseUrl: baseUrl.trim(), models: modelList, group: group.trim() || "default", priority: Number(priority) || 0, status: 1, autoBan: 0 }) }); const j = await r.json(); if (!r.ok) throw new Error(j.error || "创建渠道失败"); setOpen(false); setName(""); setModels(""); onCreated(); } catch (e) { setError(e instanceof Error ? e.message : "创建渠道失败"); } finally { setSaving(false); } };
  if (!open) return <Button size="sm" onClick={() => { setOpen(true); setError(null); }}><Plus className="h-3.5 w-3.5" />新建下游渠道</Button>;
  return <Card className="border-accent/40"><CardHeader className="flex flex-row items-center justify-between gap-3 pb-3"><div><CardTitle className="text-sm">新建下游渠道</CardTitle><p className="mt-1 text-xs text-muted">只使用已登记的绑定 Key，凭据不会返回浏览器。</p></div><Button size="sm" variant="ghost" onClick={() => setOpen(false)}>取消</Button></CardHeader><CardContent className="grid gap-3 md:grid-cols-2">{error && <Callout tone="error" className="md:col-span-2">{error}</Callout>}<div className="space-y-1.5"><Label>上游来源</Label><Select value={providerId} onChange={(e) => chooseProvider(e.target.value)}><option value="">选择上游</option>{sources.map((item) => <option key={item.providerId} value={item.providerId}>{item.providerName} · {item.type}</option>)}</Select></div><div className="space-y-1.5"><Label>绑定 Key</Label><Select value={boundKeyId} onChange={(e) => setBoundKeyId(e.target.value)} disabled={!provider}><option value="">选择绑定 Key</option>{(provider?.boundKeys || []).map((key) => <option key={key.id} value={key.id}>{key.name} · {key.keyPreview}</option>)}</Select></div><div className="space-y-1.5"><Label>渠道名称</Label><Input value={name} onChange={(e) => setName(e.target.value)} placeholder="OpenAI 主线路" /></div><div className="space-y-1.5"><Label>Base URL</Label><Input value={baseUrl} onChange={(e) => setBaseUrl(e.target.value)} placeholder="https://api.openai.com" /></div><div className="space-y-1.5 md:col-span-2"><Label>模型（逗号或换行分隔）</Label><Textarea value={models} onChange={(e) => setModels(e.target.value)} placeholder="gpt-4o\ngpt-4o-mini" /></div><div className="space-y-1.5"><Label>分组</Label><Input value={group} onChange={(e) => setGroup(e.target.value)} /></div><div className="space-y-1.5"><Label>优先级</Label><Input type="number" min="0" value={priority} onChange={(e) => setPriority(e.target.value)} /></div><div className="md:col-span-2"><Button disabled={saving} onClick={() => void submit()}>{saving ? "创建并回读中…" : "确认创建"}</Button></div></CardContent></Card>;
}
